debug: True
mqtt:
  user: "user"
  pass: "pass"
  host: "localhost"
  port: 1884
rtsp:
  stream_name: "rtsp://admin:pam1249CS1110ragot&@192.168.1.23:554//h264Preview_01_main"
  framerate: 1.0 
period_s: 0.5