debug: True
mqtt:
  user: "user"
  pass: "pass"
  host: "localhost"
  port: 1884
rtsp:
  stream_name: "rtsp://admin:pam1249CS1110ragot&@camera.local:554//h264Preview_01_main"
  framerate: 1.0
influxdb:
  url: "localhost"
  port: "8086"
  user: "user"
  pass: "pass"
  database: "telegraf"
map_generation_mean: "online"
map_generation:
  url: "http://localhost:8000/osm/{zoom}/{x}/{y}.png"
  tile_name: "osm"
period_s: 0.5